### ISSUE TITLE
Resource harness_cloudprovider_kubernetes adds new selector instead of replacing them

### ISSUE THREAD

**Issue by arimaverick** [harness/terraform-provider-harness#105] opened 2022-03-23 18:15 UTC
Hi,
### Terraform Version
1.0.0

### Affected Resource(s)
- harness_cloudprovider_kubernetes

### Expected Behavior
When selectors are updated for harness_cloudprovider_kubernetes resource, new selectors are being added instead of being replaced.

### Actual Behavior
Selectors are added to value set in delegate_selectors

### Steps to Reproduce
Create harness_cloudprovider_kubernetes resource and then try to update the delegate_selectors to a new value.

@abrahamkoshy

**Comment by micahlmartin** [comment] 2022-03-24 03:28
@arimaverick I added a test for this and I'm not seeing the behavior described here.

**Comment by micahlmartin** [comment] 2022-04-19 02:08
Unable to reproduce in the current version.

**Comment by micahlmartin** [comment] 2022-05-06 17:04
This is fixed in `v0.2.4`.

**Closed by micahlmartin** 2022-05-06 17:04 UTC
Labels: bug, waiting for response
